---
version: 0.2

phases:
  install:
    commands:
      - yum update -y --skip-broken
      - yum -y install curl jq python3-pip python3-dev perl-Digest-SHA --skip-broken
      - pip3 install --upgrade awscli
      - export PATH=$PWD/:$PATH
      - curl -o go1.17.5.linux-amd64.tar.gz https://go.dev/dl/go1.17.5.linux-amd64.tar.gz -vvv -L
      - shasum -a 256 -c <<< 'bd78114b0d441b029c8fe0341f4910370925a4d270a6a590668840675b0c653e  go1.17.5.linux-amd64.tar.gz'
      - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
      - export PATH=/usr/local/go/bin:$PATH
      - go version
      - go install github.com/sigstore/cosign/cmd/cosign@latest

  pre_build:
    commands:
      - make ecr_auth
  build:
    commands:
      - make docker_build

  post_build:
    commands:
      - make docker_push
      - make sign
      - make verify
artifacts:
  files: build.json